name: klrn-hw
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.2.2
  - python>=3.7
  - pandas=1.3.3
  - numpy
  - scipy
  - tzlocal
  - boto3
  - tqdm
  - more-itertools
  - plotly
  - tabulate
  - notebook
  - jupyter
  - ipynb-py-convert
  - nbconvert # =5.6.1
#  - jupyter_contrib_nbextensions
#  - jupyter_nbextensions_configurator
  - papermill
  - streamlit
  - boruta_py
  - optuna
  - pip:
    - scikit-learn==1.0
    - sagemaker
    - xgboost==1.3.1 # important to have the same version as in AWS
